name: "Labeler: Predict (Pulls)"

on:
  # Per to the following documentation:
  # https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request_target
  #
  # The `pull_request_target` event runs in the context of the base of the pull request, rather
  # than in the context of the merge commit, as the `pull_request` event does. This prevents
  # execution of unsafe code from the head of the pull request that could alter the repository
  # or steal any secrets you use in your workflow. This event allows your workflow to do things
  # like label or comment on pull requests from forks.
  #
  # Only automatically predict area labels when pull requests are first opened
  pull_request_target:
    types: opened

  # Allow dispatching the workflow via the Actions UI, specifying ranges of numbers
  workflow_dispatch:
    inputs:
      pulls:
        description: "Pull Numbers (comma-separated list of ranges)"
        type: string
        required: true
      cache_key:
        description: "The cache key suffix to use for loading the model"
        type: string
        required: true
        default: "ACTIVE"

env:
  LABEL_PREFIX: "area-"
  THRESHOLD: 0.40
  DEFAULT_LABEL: "needs-area-label"
  EXCLUDED_AUTHORS: null

jobs:
  predict-pull-label:
    # Do not run the workflow on forks outside the 'jeffhandley' org
    if: ${{ github.repository_owner == 'jeffhandley' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: "Restore pulls model from cache"
        id: restore-model
        uses: jeffhandley/issue-labeler/restore@main
        with:
          type: pulls
          fail-on-cache-miss: ${{ github.event_name == 'workflow_dispatch' }}

      - name: "Predict pull labels"
        id: prediction
        if: ${{ steps.restore-model.outputs.cache-hit == 'true' }}
        uses: jeffhandley/issue-labeler/predict@main
        with:
          pulls:            ${{ inputs.pulls || github.event.number }}
          label_prefix:     ${{ env.LABEL_PREFIX }}
          threshold:        ${{ env.THRESHOLD }}
          default_label:    ${{ env.DEFAULT_LABEL }}
          excluded_authors: ${{ env.EXCLUDED_AUTHORS }}
        env:
          GITHUB_TOKEN:  ${{ github.token }}
        continue-on-error: ${{ github.event_name == 'pull_request_target' }}

      - name: "Show prediction"
        if: ${{ steps.restore-model.outputs.cache-hit == 'true' && github.event_name == 'issues' }}
        shell: bash
        run: |
          echo "Predicted Label: ${{ steps.prediction.outputs.label }}" >> $GITHUB_STEP_SUMMARY
          echo "Prediction Score: ${{ steps.prediction.outputs.score }}" >> $GITHUB_STEP_SUMMARY
